apiVersion: v1
kind: Service
metadata:
  name: slurm-controller-svc
spec:
  selector:
    app: slurm-controller-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 8080 #Container port
  type: ClusterIP
