apiVersion: v1
kind: Service
metadata:
  name: example-service
spec:
  selector:
    app: example
  ports:
    - port: 8765
      targetPort: 9376
  externalIPs:
    - "10.0.1.50"
  type: LoadBalancer
